<!DOCTYPE html SYSTEM "about:legacy-compat">
<html lang="en-US" data-preset="contrast" data-primary-color="#307FFF"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta charset="UTF-8"><meta name="robots" content="noindex"><meta name="built-on" content="2024-11-29T17:03:54.995506"><title>Lan&ccedil;ando uma exce&ccedil;&atilde;o | Conteúdo do Curso Python para Dynamo do Revit</title><script type="application/json" id="virtual-toc-data">[{"id":"descri-o","level":0,"title":"Descrição","anchor":"#descri-o"},{"id":"exemplo","level":0,"title":"Exemplo","anchor":"#exemplo"},{"id":"onde-encontrar-as-exce-es-mais-comuns-lan-adas-pelo-python","level":0,"title":"Onde encontrar as exceções mais comuns lançadas pelo Python?","anchor":"#onde-encontrar-as-exce-es-mais-comuns-lan-adas-pelo-python"},{"id":"exerc-cio","level":0,"title":"Exercício","anchor":"#exerc-cio"}]</script><script type="application/json" id="topic-shortcuts"></script><link href="https://resources.jetbrains.com/writerside/apidoc/6.10.0-b518/app.css" rel="stylesheet"><meta name="msapplication-TileColor" content="#000000"><link rel="apple-touch-icon" sizes="180x180" href="https://jetbrains.com/apple-touch-icon.png"><link rel="icon" type="image/png" sizes="32x32" href="https://jetbrains.com/favicon-32x32.png"><link rel="icon" type="image/png" sizes="16x16" href="https://jetbrains.com/favicon-16x16.png"><meta name="msapplication-TileImage" content="https://resources.jetbrains.com/storage/ui/favicons/mstile-144x144.png"><meta name="msapplication-square70x70logo" content="https://resources.jetbrains.com/storage/ui/favicons/mstile-70x70.png"><meta name="msapplication-square150x150logo" content="https://resources.jetbrains.com/storage/ui/favicons/mstile-150x150.png"><meta name="msapplication-wide310x150logo" content="https://resources.jetbrains.com/storage/ui/favicons/mstile-310x150.png"><meta name="msapplication-square310x310logo" content="https://resources.jetbrains.com/storage/ui/favicons/mstile-310x310.png"><meta name="image" content=""><!-- Open Graph --><meta property="og:title" content="Lan&ccedil;ando uma exce&ccedil;&atilde;o | Conteúdo do Curso Python para Dynamo do Revit"><meta property="og:description" content=""><meta property="og:image" content=""><meta property="og:site_name" content="Conteúdo do Curso Python para Dynamo do Revit Help"><meta property="og:type" content="website"><meta property="og:locale" content="en_US"><meta property="og:url" content="writerside-documentation/raise-an-exception.html"><!-- End Open Graph --><!-- Twitter Card --><meta name="twitter:card" content="summary_large_image"><meta name="twitter:site" content=""><meta name="twitter:title" content="Lan&ccedil;ando uma exce&ccedil;&atilde;o | Conteúdo do Curso Python para Dynamo do Revit"><meta name="twitter:description" content=""><meta name="twitter:creator" content=""><meta name="twitter:image:src" content=""><!-- End Twitter Card --><!-- Schema.org WebPage --><script type="application/ld+json">{
    "@context": "http://schema.org",
    "@type": "WebPage",
    "@id": "writerside-documentation/raise-an-exception.html#webpage",
    "url": "writerside-documentation/raise-an-exception.html",
    "name": "Lan&ccedil;ando uma exce&ccedil;&atilde;o | Conteúdo do Curso Python para Dynamo do Revit",
    "description": "",
    "image": "",
    "inLanguage":"en-US"
}</script><!-- End Schema.org --><!-- Schema.org WebSite --><script type="application/ld+json">{
    "@type": "WebSite",
    "@id": "writerside-documentation/#website",
    "url": "writerside-documentation/",
    "name": "Conteúdo do Curso Python para Dynamo do Revit Help"
}</script><!-- End Schema.org --></head><body data-id="raise-an-exception" data-main-title="Lançando uma exceção" data-article-props="{&quot;seeAlsoStyle&quot;:&quot;links&quot;}" data-template="article" data-breadcrumbs="Aula-003.md|Aula 003///exceptions.md|Exceções"><div class="wrapper"><main class="panel _main"><header class="panel__header"><div class="container"><h3>Conteúdo do Curso Python para Dynamo do Revit  Help</h3><div class="panel-trigger"></div></div></header><section class="panel__content"><div class="container"><article class="article" data-shortcut-switcher="inactive"><h1 data-toc="raise-an-exception" id="raise-an-exception.md">Lançando uma exceção</h1><section class="chapter"><h2 id="descri-o" data-toc="descri-o">Descri&ccedil;&atilde;o</h2><p id="-smumpc_7">&Eacute; interessante algumas vezes fazermos com que nossos m&eacute;todos lancem exce&ccedil;&otilde;es espec&iacute;ficas para deixar nosso c&oacute;digo mais consistente e f&aacute;cil e depurar.</p><p id="-smumpc_8">Para fazer isso usamos o comando <code class="code" id="-smumpc_10">raise</code>.</p><p id="-smumpc_9">O comando <code class="code" id="-smumpc_11">raise</code> em Python &eacute; usado para lan&ccedil;ar exce&ccedil;&otilde;es, permitindo que voc&ecirc; interrompa a execu&ccedil;&atilde;o normal do programa e sinalize a ocorr&ecirc;ncia de um erro.</p></section><section class="chapter"><h2 id="exemplo" data-toc="exemplo">Exemplo</h2><p id="-smumpc_12">Suponha que temos uma fun&ccedil;&atilde;o que verifica a idade de uma pessoa e s&oacute; permite a entrada se a pessoa tiver 18 anos ou mais. Se a idade for menor que 18, a fun&ccedil;&atilde;o lan&ccedil;ar&aacute; uma exce&ccedil;&atilde;o personalizada.</p><div class="code-block" data-lang="python">
def dividir_numeros(a, b):
    try:
        resultado = a / b
        print(f&quot;O resultado da divisão é: {resultado}&quot;)
    except ZeroDivisionError:
        print(&quot;Erro: Não é possível dividir por zero!&quot;)

# Exemplo de usodividir_numeros(10, 0)
</div><section class="chapter"><h3 id="explica-o-do-c-digo" data-toc="explica-o-do-c-digo">Explica&ccedil;&atilde;o do C&oacute;digo:</h3><ol class="list _decimal" id="-smumpc_15" type="1"><li class="list__item" id="-smumpc_16"><p><span class="control" id="-smumpc_18">Bloco try</span>: </p><ul class="list _bullet" id="-smumpc_19"><li class="list__item" id="-smumpc_20"><p>Tentamos dividir <code class="code" id="-smumpc_22">a</code> por <code class="code" id="-smumpc_23">b</code> e armazenar o resultado.</p></li><li class="list__item" id="-smumpc_21"><p>Se a divis&atilde;o for bem-sucedida, o resultado &eacute; impresso.</p></li></ul></li><li class="list__item" id="-smumpc_17"><p><span class="control" id="-smumpc_24">Bloco except</span>: </p><ul class="list _bullet" id="-smumpc_25"><li class="list__item" id="-smumpc_26"><p>Captura a exce&ccedil;&atilde;o <code class="code" id="-smumpc_27">ZeroDivisionError</code> se <code class="code" id="-smumpc_28">b</code> for zero e imprime uma mensagem de erro apropriada.</p></li></ul></li></ol></section></section><section class="chapter"><h2 id="onde-encontrar-as-exce-es-mais-comuns-lan-adas-pelo-python" data-toc="onde-encontrar-as-exce-es-mais-comuns-lan-adas-pelo-python">Onde encontrar as exce&ccedil;&otilde;es mais comuns lan&ccedil;adas pelo Python?</h2><p id="-smumpc_29">Voc&ecirc; pode encontrar uma lista das exce&ccedil;&otilde;es mais comuns lan&ccedil;adas pelo Python na <a href="https://docs.python.org/pt-br/3/library/exceptions.html?formCode=MG0AV3" id="-smumpc_33" data-external="true" rel="noopener noreferrer"><span class="control" id="-smumpc_34">documenta&ccedil;&atilde;o oficial do Python</span></a>.</p><p id="-smumpc_30">Aqui est&atilde;o algumas das exce&ccedil;&otilde;es mais comuns:</p><ul class="list _bullet" id="-smumpc_31"><li class="list__item" id="-smumpc_35"><p><span class="control" id="-smumpc_45"><code class="code" id="-smumpc_47">AssertionError</code></span>: gerada quando uma instru&ccedil;&atilde;o <code class="code" id="-smumpc_46">assert</code> falha.</p></li><li class="list__item" id="-smumpc_36"><p><span class="control" id="-smumpc_48"><code class="code" id="-smumpc_50">EOFError</code></span>: gerada quando a fun&ccedil;&atilde;o <code class="code" id="-smumpc_49">input()</code> atende &agrave; condi&ccedil;&atilde;o de fim de arquivo.</p></li><li class="list__item" id="-smumpc_37"><p><span class="control" id="-smumpc_51"><code class="code" id="-smumpc_52">AttributeError</code></span>: gerada quando uma atribui&ccedil;&atilde;o ou refer&ecirc;ncia de atributo falha.</p></li><li class="list__item" id="-smumpc_38"><p><span class="control" id="-smumpc_53"><code class="code" id="-smumpc_54">TabError</code></span>: gerada quando os recuos consistem em tabula&ccedil;&otilde;es ou espa&ccedil;os inconsistentes.</p></li><li class="list__item" id="-smumpc_39"><p><span class="control" id="-smumpc_55"><code class="code" id="-smumpc_56">ImportError</code></span>: gerada quando a importa&ccedil;&atilde;o de um m&oacute;dulo falha.</p></li><li class="list__item" id="-smumpc_40"><p><span class="control" id="-smumpc_57"><code class="code" id="-smumpc_58">IndexError</code></span>: gerada quando um &iacute;ndice est&aacute; fora do intervalo v&aacute;lido.</p></li><li class="list__item" id="-smumpc_41"><p><span class="control" id="-smumpc_59"><code class="code" id="-smumpc_60">KeyError</code></span>: gerada quando uma chave n&atilde;o est&aacute; presente em um dicion&aacute;rio.</p></li><li class="list__item" id="-smumpc_42"><p><span class="control" id="-smumpc_61"><code class="code" id="-smumpc_62">ValueError</code></span>: gerada quando uma fun&ccedil;&atilde;o recebe um argumento de valor incorreto.</p></li><li class="list__item" id="-smumpc_43"><p><span class="control" id="-smumpc_63"><code class="code" id="-smumpc_64">TypeError</code></span>: gerada quando uma opera&ccedil;&atilde;o &eacute; aplicada a um objeto de um tipo inapropriado.</p></li><li class="list__item" id="-smumpc_44"><p><span class="control" id="-smumpc_65"><code class="code" id="-smumpc_66">ZeroDivisionError</code></span>: gerada quando se tenta dividir por zero.</p></li></ul><p id="-smumpc_32">Essas exce&ccedil;&otilde;es s&atilde;o padr&atilde;o no Python e s&atilde;o usadas para lidar com diferentes tipos de erros que podem ocorrer durante a execu&ccedil;&atilde;o de um programa.</p></section><section class="chapter"><h2 id="exerc-cio" data-toc="exerc-cio">Exerc&iacute;cio</h2><p id="-smumpc_67">Melhorar a execu&ccedil;&atilde;o do c&oacute;digo de <a href="número.html#equacao-segundo-grau" id="-smumpc_68" data-tooltip="Fazer um script para calcular as raízes de uma equação do segundo grau.">c&aacute;culo da equa&ccedil;&atilde;o do segundo grau</a>, lan&ccedil;ando exce&ccedil;&otilde;es espec&iacute;ficas para onde houver problemas:</p></section><div class="last-modified">Last modified: 29 November 2024</div><div data-feedback-placeholder="true"></div><div class="navigation-links _bottom"><a href="try-except.html" class="navigation-links__prev">try-except</a><a href="catching-revit-exceptions.html" class="navigation-links__next">Capturando exce&ccedil;&otilde;es lan&ccedil;adas pelo Revit</a></div></article><div id="disqus_thread"></div></div></section></main></div><script src="https://resources.jetbrains.com/writerside/apidoc/6.10.0-b518/app.js"></script></body></html>